"""empty message

Revision ID: 324b2e1d3cfa
Revises: 60a459cf9d79
Create Date: 2023-08-02 12:19:09.593449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324b2e1d3cfa'
down_revision = '60a459cf9d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_details',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_order_details_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_order_details_user_id_user')),
    sa.PrimaryKeyConstraint('product_id', 'user_id', name=op.f('pk_order_details'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    # ### end Alembic commands ###
