"""empty message

Revision ID: 50984003f8f1
Revises: 324b2e1d3cfa
Create Date: 2023-08-04 13:45:29.224849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50984003f8f1'
down_revision = '324b2e1d3cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name=op.f('fk_approval_category_id_category')),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], name=op.f('fk_approval_manager_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval')
    # ### end Alembic commands ###
