"""

Revision ID: 60a459cf9d79
Revises: f21cad9cdcae
Create Date: 2023-08-02 09:39:10.573425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a459cf9d79'
down_revision = 'f21cad9cdcae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cart')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_cart_product_id_product', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cart_id_product'), 'product', ['id'], ['product_id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_cart_id_product'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_product_id_product', 'product', ['product_id'], ['product_id'])
        batch_op.drop_column('id')

    op.create_table('_alembic_tmp_cart',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rate', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['product.product_id'], name='fk_cart_id_product'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cart_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', name='pk_cart')
    )
    # ### end Alembic commands ###
