"""

Revision ID: ab90fd80c3e8
Revises: c0259bfd89c9
Create Date: 2023-08-02 09:25:45.932563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab90fd80c3e8'
down_revision = 'c0259bfd89c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_cart_product_id_product', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cart_id_product'), 'product', ['id'], ['product_id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('order_id')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_name')
        batch_op.drop_column('rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_cart_id_product'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_product_id_product', 'product', ['product_id'], ['product_id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###
