"""yes

Revision ID: c0259bfd89c9
Revises: 
Create Date: 2023-07-28 20:38:56.256944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0259bfd89c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_category'))
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('rate_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('m_date', sa.Date(), nullable=False),
    sa.Column('e_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], name=op.f('fk_product_category_id_category')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product'))
    )
    op.create_table('cart',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_cart_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cart_user_id_user')),
    sa.PrimaryKeyConstraint('product_id', 'user_id', name=op.f('pk_cart'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_orders_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_orders_user_id_user')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('cart')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
