"""empty message

Revision ID: e99c1badcead
Revises: a7799450721e
Create Date: 2023-08-07 15:55:34.512139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c1badcead'
down_revision = 'a7799450721e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
