"""empty message

Revision ID: f21cad9cdcae
Revises: ab90fd80c3e8
Create Date: 2023-08-02 09:34:30.252110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21cad9cdcae'
down_revision = 'ab90fd80c3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_orders_product_id_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_orders_user_id_user')),
    sa.PrimaryKeyConstraint('product_id', 'user_id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_cart_product_id_product', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cart_id_product'), 'product', ['id'], ['product_id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_cart_id_product'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_product_id_product', 'product', ['product_id'], ['product_id'])
        batch_op.drop_column('id')

    op.drop_table('orders')
    # ### end Alembic commands ###
